-- CreateTable
CREATE TABLE `PLAYER` (
    `PL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PL_NAME` VARCHAR(45) NOT NULL,
    `PL_EMAIL` VARCHAR(100) NOT NULL,
    `PL_PASSWORD_HASH` VARCHAR(255) NOT NULL,
    `PL_COINS` INTEGER NOT NULL DEFAULT 0,
    `PL_GEMS` INTEGER NOT NULL DEFAULT 0,
    `PL_LEVEL` INTEGER NOT NULL DEFAULT 1,
    `PL_AVATAR` VARCHAR(255) NULL,
    `PL_LIFE` INTEGER NOT NULL DEFAULT 100,
    `PL_Created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PLAYER_PL_NAME_key`(`PL_NAME`),
    UNIQUE INDEX `PLAYER_PL_EMAIL_key`(`PL_EMAIL`),
    PRIMARY KEY (`PL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CARDS` (
    `CD_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CD_NAME` VARCHAR(100) NOT NULL,
    `CD_DESCRIPTION` VARCHAR(255) NOT NULL,
    `CD_TYPE` VARCHAR(50) NOT NULL,
    `CD_COST` INTEGER NOT NULL,
    `CD_LIFE` INTEGER NULL,
    `CD_ATTACK` INTEGER NULL,
    `CD_DEFENSE` INTEGER NULL,
    `CD_IMAGE` VARCHAR(255) NULL,

    UNIQUE INDEX `CARDS_CD_NAME_key`(`CD_NAME`),
    PRIMARY KEY (`CD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PLAYER_CARD` (
    `PLAYER_PL_ID` INTEGER NOT NULL,
    `CARDS_CD_ID` INTEGER NOT NULL,
    `PL_CD_QUANTITY` INTEGER NOT NULL,

    PRIMARY KEY (`PLAYER_PL_ID`, `CARDS_CD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DECK` (
    `DECK_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DECK_NAME` VARCHAR(100) NOT NULL,
    `DECK_IS_ACTIVE` BOOLEAN NOT NULL DEFAULT false,
    `PLAYER_PL_ID` INTEGER NOT NULL,
    `DECK_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`DECK_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DECK_CARD` (
    `DECK_ID` INTEGER NOT NULL,
    `CARDS_CD_ID` INTEGER NOT NULL,
    `DECK_CD_QUANTITY` INTEGER NOT NULL,

    PRIMARY KEY (`DECK_ID`, `CARDS_CD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MATCH` (
    `MT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MT_START_TIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `MT_END_TIME` DATETIME(3) NULL,
    `MT_TYPE` VARCHAR(50) NOT NULL,
    `MT_WINNER_ID` INTEGER NULL,

    PRIMARY KEY (`MT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MATCH_PLAYER` (
    `MATCH_ID` INTEGER NOT NULL,
    `PLAYER_ID` INTEGER NOT NULL,
    `DECK_USED_ID` INTEGER NOT NULL,
    `MT_PL_FINAL_LIFE` INTEGER NOT NULL,
    `MT_PL_IS_WINNER` BOOLEAN NOT NULL,

    PRIMARY KEY (`MATCH_ID`, `PLAYER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PLAYER_CARD` ADD CONSTRAINT `PLAYER_CARD_PLAYER_PL_ID_fkey` FOREIGN KEY (`PLAYER_PL_ID`) REFERENCES `PLAYER`(`PL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PLAYER_CARD` ADD CONSTRAINT `PLAYER_CARD_CARDS_CD_ID_fkey` FOREIGN KEY (`CARDS_CD_ID`) REFERENCES `CARDS`(`CD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DECK` ADD CONSTRAINT `DECK_PLAYER_PL_ID_fkey` FOREIGN KEY (`PLAYER_PL_ID`) REFERENCES `PLAYER`(`PL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DECK_CARD` ADD CONSTRAINT `DECK_CARD_DECK_ID_fkey` FOREIGN KEY (`DECK_ID`) REFERENCES `DECK`(`DECK_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DECK_CARD` ADD CONSTRAINT `DECK_CARD_CARDS_CD_ID_fkey` FOREIGN KEY (`CARDS_CD_ID`) REFERENCES `CARDS`(`CD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MATCH` ADD CONSTRAINT `MATCH_MT_WINNER_ID_fkey` FOREIGN KEY (`MT_WINNER_ID`) REFERENCES `PLAYER`(`PL_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MATCH_PLAYER` ADD CONSTRAINT `MATCH_PLAYER_MATCH_ID_fkey` FOREIGN KEY (`MATCH_ID`) REFERENCES `MATCH`(`MT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MATCH_PLAYER` ADD CONSTRAINT `MATCH_PLAYER_PLAYER_ID_fkey` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYER`(`PL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MATCH_PLAYER` ADD CONSTRAINT `MATCH_PLAYER_DECK_USED_ID_fkey` FOREIGN KEY (`DECK_USED_ID`) REFERENCES `DECK`(`DECK_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
